### ISSUE TITLE
Can the Livox AVIA, using the Livox ROS Driver 1 be supported ?

### ISSUE THREAD

**Issue by MattiasTancred** [davidskdds/DMSA_LiDAR_SLAM#8]
I currently use this repo with the Livox MID360 and achieve excellent results. I would like to try the Livox AVIA, which uses the Livox ROS Driver 1 and outputs point clouds in the PointXYZRTL format.

All suggestions are welcome!

**Comment by davidskdds** [comment]
Hello,
thank you for the feedback.
Regarding your question:
The problem with the PointXYZRTL-format is that there are no time stamps per point provided, which are important for accurate results.

But there is a solution you can try. In case of unknown sensor approx. time stamps per point can be interpolated.

Therefore set the following parameters in the config:
sensor: "unknown"

Reduce also the number of points (small fov):
max_num_points_per_scan: 1500 (if 1500 does not work, try 1000)

With these settings there is a good chance you get some plausible results.

Best regards
David

**Comment by MattiasTancred** [comment]
Thanks for the input. 

DMSA_LIDAR_SLAM repo seems to work as suggested and creates a pointcloud. But trying to create a densepointcloud with dense_cloud_creator does not work. Any suggestions? 
![Skärmbild från 2024-12-04 16-36-54](https://github.com/user-attachments/assets/d115b461-05ab-498f-aabf-242348707af3)
![Skärmbild från 2024-12-04 16-37-03](https://github.com/user-attachments/assets/d97d4767-95d8-469c-a51b-79e17b961789)

**Comment by davidskdds** [comment]
Hello, I just tried to reproduce your error with a rosbag of a livox Mid-40 and the sensor mode "unknown". First I run the dmsa slam to create a pose file, then I run the dense_cloud_creator. It worked fine in my case.

I recommend that you check the .yaml config in the dense_cloud_creator again to see if the sensor “unknown” is also set here and also the correct rosbag is selected. If dont find an error there, I can offer you to send me the rosbag and your pose file, then I can try to find the error.

Best regards
David

**Comment by MattiasTancred** [comment]
I previously used the factory translation values for the IMU and LiDAR in the YAML file. After changing the translation parameters to t_x: 0.0, t_y: 0.0, and t_z: 0.0, and setting acceleration_in_g: false, I achieved pretty good results with the AVIA LiDAR...sensor mode "unkown".

**Comment by davidskdds** [comment]
Okay perfect, I'm glad to hear that

**Comment by 85256638** [comment]
@MattiasTancred , Hi, could you let me know how accurate the dense point cloud created by DMA is comparing with the one generated by FastLIO2? Thanks! I might give it a try by using Livox Horizon.

**Comment by MattiasTancred** [comment]
I find that DMSA consistently yields better point clouds than FastLIO2, especially in tighter, more complex indoor environments such as stairwells, corridors, and other multi-level spaces. I haven’t tested FastLIO2 extensively.

**Comment by 85256638** [comment]
> I find that DMSA consistently yields better point clouds than FastLIO2, especially in tighter, more complex indoor environments such as stairwells, corridors, and other multi-level spaces. I haven’t tested FastLIO2 extensively.

Thanks a lot for sharing your exprience, much appreciated! My use case is mainly the in-door environments.
